# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0067_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/license')),
            ],
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/photo'),
        ),
    ]
