# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0068_auto_20170927_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='license_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.UserLicense'),
        ),
    ]
