# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0069_userprofile_license_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_approved',
            field=models.BooleanField(default=False),
        ),
    ]
