# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0074_userprofile_notifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
