# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0075_auto_20171004_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
