# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0076_userprofile_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_approved',
            field=models.BooleanField(default=False),
        ),
    ]
